### ISSUE TITLE
Enabling SystemdCgroup in containerd config not working

### ISSUE THREAD

**Issue by vielfarbig** [torgeirl/kubernetes-playbooks#18]
Hello,

thank you for work on a (mostly) working ansible deployment for kubernetes.
I don't use the terraform/OpenStack deployments, but rather only the ansible playbooks.

If I only deploy with the ansible playbooks, the flannel and kube-proxy gets stuck in a CrashLoopBackOff, which I have traced back to the origin of not having SystemdCgroup enabled in containerd config. The current replace task therefore does not work.

I fixed it by the following:
```
    - name: configuring the systemd cgroup for containerd
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '            SystemdCgroup = false'
        line: '            SystemdCgroup = true'
```
I also successfully use the 1.26.* version for the kubernetes tools.
