### ISSUE TITLE
Allocatable values for nodes 

### ISSUE THREAD

**Issue by torgeirl** [torgeirl/kubernetes-playbooks#4]
To improve scheduling we should set [reserved allocatable values](https://v1-17.docs.kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/) for the nodes.

This has to be set during cluster initialization. There isn't a flag for it, and it isn't possible to combine flags with config files so other flags has to be included in the config file.

We currently only specify the subnet range that will be broken down and handed out to each node with the `--pod-network-cidr` flag:

```console
kubeadm init --pod-network-cidr=10.244.0.0/16
```

From what I have found the following YAML file should both set pod subnet and provide the needed information to set allocatable values for our nodes:

```YAML
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
networking:
  podSubnet: 10.244.0.0/16
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
systemReservedCgroup: systemreserved
kubeReservedCgroup: podruntime
cgroupRoot: /
systemReserved:
  cpu: 100m
  memory: 400M
kubeReserved:
  cpu: 100m
  memory: 100M
enforceNodeAllocatable:
- pods
- system-reserved
- kube-reserved
```

kubeadm is however unable to initialize the cluster when provided with this config (and several permutations of it):

```console
$ kubeadm init --config=kubeadm-init.yaml
Error: can't initialize Kubernetes cluster
```
